### PR TITLE
Milestone 1

### PR DESCRIPTION
**Pull request by wozniakty**

### CODE REVIEW

**Comment by dislogical** [comment]
:+1:

**Comment by PxlBuzzard** [comment]
Game team approves

**Comment by brooklynlittell** [comment]
Doesn't render on my computer! Yay! :poop:

**Comment by ericchristenson** [comment]
#25 For Rendering issues

**Comment by ScrappyOrc** [comment]
Doesn't render on my laptop, but appears to render on other machines. So I approve

**Pull request merged**
