### PR TITLE
Feature: Point Lighting & Specular

### PR DESCRIPTION
**Pull request by ericchristenson**
You must be on Sample game's dash-point-lights branch to test this.

### CODE REVIEW

**Comment by dislogical** [comment]
Looks great! With dem polys it runs at a stable 13 fps on my Air.

Could you guys merge `develop` into your branch so the merge is easier?

**Comment by brooklynlittell** [comment]
:+1:

**Comment by wozniakty** [comment]
:+1:

**Comment by ericchristenson** [comment]
Check again, things should be better and up to date with develop now.

**Comment by wozniakty** [comment]
Much better.

**Comment by ericchristenson** [comment]
also closes #18 and #48

**Pull request merged**
