### PR TITLE
Feature: Animation System

### PR DESCRIPTION
**Pull request by tmr9209**
Major animation push:
-Fully working animation system, tested with fbxtest and wolf
-Pause/play/stop working
-Comments/documentation completed
-Renaming/cleaning up
-Animating based on deltaTime

### CODE REVIEW

**Comment by dislogical** [comment]
Tabs -> Spaces, then LGTM

**Comment by dislogical** [comment]
:a:

**Comment by brooklynlittell** [comment]
:+1:

**Comment by ericchristenson** [comment]
:+1:

**Comment by wozniakty** [comment]
:+1:

**Pull request merged**
