### PR TITLE
Feature: Shared Transforms

### LINKED ISSUE #93: Modification of individual position members
Programmatically changing the individual x,y,z members of the transform object in GO appears to be broken. Current workaround: set position equal to a new vec3.

### PR DESCRIPTION
**Pull request by dislogical**
This pull request ports all members of `Transform` to be native shared objects, meaning that there is no `cast()`ing required to use.

Closes #93.

### CODE REVIEW

**Comment by brooklynlittell** [comment]
Looks great! :+1: Realllly cleans up that shared code (the cast()'s). :smile:

**Comment by brooklynlittell** [comment]
This also fixes #93.

**Comment by ericchristenson** [comment]
Hurraaaaay

**Comment by wozniakty** [comment]
So will developers writing in our engine need to add the shared keyword to gl3n types now?

**Comment by dislogical** [comment]
Yes, just like how they'll need to use `shared` with most of the rest of the engine.

**Pull request merged**
