### PR TITLE
Fix for AMD cards

### PR DESCRIPTION
**Pull request by ericchristenson**
Everyone, even if you didn't have issues, should pull and test so we know if this is fixed for sure or not.
So far we've had success on my and Brandon's machines.

### CODE REVIEW

**Comment by brooklynlittell** [comment]
This worked for my machine.

**Comment by ScrappyOrc** [comment]
Worked for me! (On AMD 6990M, windows 7)

**Comment by wozniakty** [comment]
Hmm.  I wonder why the same change didn't need to be made for the lighting pass

**Comment by dislogical** [comment]
Works on my Air.

**Comment by wozniakty** [comment]
:+1:

**Comment by dislogical** [comment]
So is this all set to merge?

**Comment by wozniakty** [comment]
Seems like it.  I'd say go ahead.

**Comment by dislogical** [comment]
@ericchristenson go!

**Comment by brooklynlittell** [comment]
He's probably asleep. I'll push the button.

**Pull request merged**
