### PR TITLE
Feature: Task Scheduling

### LINKED ISSUE #102: Add a scheduler function
Either return a bool or make it time-based.

### PR DESCRIPTION
**Pull request by dislogical**
Allows you to schedule tasks to execute over a given period of time, or until it returns true.

Closes #102.

Relies on #103.

See [feature/TaskScheduling on Sample Dash Game](https://github.com/Circular-Studios/Sample-Dash-Game/tree/feature/TaskScheduling).

### CODE REVIEW

**Comment by wozniakty** [comment]
Check travis build.  Doesn't like a particular cast in dgame

**Comment by dislogical** [comment]
Oooh, I see. This is a linux specific issue. Apparently Windows uses `uint`s for array indicies, where as linux uses `long`s. I think I have a fix for it, though.

**Comment by brooklynlittell** [comment]
:+1:

**Comment by ericchristenson** [comment]
:100:

**Pull request merged**
