### PR TITLE
Version 0.6.0

### PR DESCRIPTION
**Pull request by wozniakty**
Major changes for version 0.6.0 include mouse support, a more consistent graphics pipeline, change to GameStates, improvements to the Time utility, a transition from a GameObjectCollection to Scenes, and functional animations.

[Issues Closed](https://github.com/Circular-Studios/Dash/issues?milestone=6&state=closed)

### CODE REVIEW

**Comment by PxlBuzzard** [comment]
:penguin:

**Comment by tmr9209** [comment]
Looks good

**Comment by dislogical** [comment]
:a:

**Comment by brooklynlittell** [comment]
:+1:

**Comment by ericchristenson** [comment]
:100:

**Comment by dislogical** [comment]
:shipit:

**Comment by wozniakty** [comment]
Travis build suddenly giving weird errors.  Any idea @ColdenCullen?

**Comment by dislogical** [comment]
Looks like @ericchristenson 's commit broke it. Eric, any ideas?

**Comment by ericchristenson** [comment]
I moved some private: variables from the bottom of classes to the top, so only if that would fail somehow...

**Comment by dislogical** [comment]
Does it build on your machine?

**Comment by dislogical** [comment]
Build passed. We good to merge?

**Pull request merged**
