### PR TITLE
Feature: Fast Refreshing

### PR DESCRIPTION
**Pull request by dislogical**
This does a few things:
1. Deprecates filepath.d in favor of resources.d
2. Added `Asset` abstract class for art assets, which keep track usage and source file path.
3. Implemented refreshing (as opposed to resetting), which updates Graphics, Config, Prefabs, Textures, Meshes, and Materials (pretty much everything that's not an object) in real time without changing any state. Reload still exists for when objects change.

Feedback, as always, is absolutely welcome.

### CODE REVIEW

**Comment by PxlBuzzard** [comment]
Do you see refresh being bound to a button or getting handled more automatically?

**Comment by dislogical** [comment]
All calls will be manual, but you could setup a task that refreshes it every X seconds when in debug mode using [`scheduleIntervaledTask`](http://circular-studios.github.io/Dash/docs/latest/utility/tasks/scheduleIntervaledTask.html) like this:

``` d
scheduleIntervaledTask( 5.seconds, { currentState = EngineState.Refresh; return false; } );
```

**Comment by dislogical** [comment]
Updated to support object refreshing.

**Comment by ericchristenson** [comment]
Looks good

**Comment by wozniakty** [comment]
:+1:

**Pull request merged**
