### PR TITLE
Feature: Component Decentralization

### PR DESCRIPTION
**Pull request by dislogical**
This moves all Component Creation code into the modules for that component to allow for users to create their own components.

### CODE REVIEW

**Comment by wozniakty** [comment]
So, if I understand this correctly, components load their yaml data statically and then we essentially read the object/prefab yamls to pull in those components?

**Comment by dislogical** [comment]
Not quite. The code still runs in the same order it did, except that the code for actually parsing the yaml has been moved out of `GameObject.createFromYaml()` and into the respective module.

**Comment by brooklynlittell** [comment]
:+1:

**Comment by wozniakty** [comment]
:+1:

**Comment by ericchristenson** [comment]
Good as far as I know, hopefully nothing else went missing.

**Pull request merged**
