### PR TITLE
Cleanup: Imports

### PR DESCRIPTION
**Pull request by dislogical**
Added package.d to all packages, and cleaned up imports to be only packages.

I don't feel particularly strongly about this, and it's open to discussion.

### CODE REVIEW

**Comment by tmr9209** [comment]
It looks good to me. (I like that it cleans up some of the imports)

**Comment by wozniakty** [comment]
I approve :+1:

**Comment by brooklynlittell** [comment]
Looks great! :+1:

**Comment by ericchristenson** [comment]
Good enough

**Pull request merged**
