### PR TITLE
Feature: Prefabs

### PR DESCRIPTION
**Pull request by dislogical**
This is a super basic system that allows you to create instances of prefabs.

### CODE REVIEW

**Comment by dislogical** [comment]
The only limitation to this current system is that you cannot override the Script field.

**Comment by dislogical** [comment]
That's a good question, and it should certainly go up for discussion. I would guess we would want to make copies of the view, not shared references.

**Comment by wozniakty** [comment]
Looks solid.  Question: do we foresee a prefab holding it's material, or will we grab that somewhere else?

**Comment by dislogical** [comment]
I think the materials should managed by something else, but I think a material could be stored in the component references list.

**Comment by wozniakty** [comment]
:+1:

**Comment by tmr9209** [comment]
Looks good

**Comment by brooklynlittell** [comment]
:+1:

**Pull request merged**
