### PR TITLE
Feature: Animation system

### PR DESCRIPTION
**Pull request by tmr9209**
Merge animation system into develop.

### CODE REVIEW

**Comment by wozniakty** [comment]
:+1:

**Comment by dislogical** [comment]
:a:

**Comment by brooklynlittell** [comment]
Are we not worried about Travis?

**Comment by dislogical** [comment]
It's an awesomium thing. I'm working on it now.

**Comment by brooklynlittell** [comment]
Ah, so it is. Missed that. This gets a :+1:

**Comment by dislogical** [comment]
@tmr9209 If there's anything in Sample Game that needs to be merged, do that now.

**Pull request merged**
