### PR TITLE
Feature: Mouse Input

### LINKED ISSUE #9: Mouse Support
We need to be able to click on things. This means we need to do a raytrace (or something similar) and return the first object on the screen.

### PR DESCRIPTION
**Pull request by wozniakty**
This is the initial mouse input solution.  This will be more than sufficient for specific atomic mouse interactions for current test projects.

This solution will need to improve in order to have efficient per-frame mouse tracking, but is feature complete for the current milestone.

Closes #9.

### CODE REVIEW

**Comment by wozniakty** [comment]
This branch follows the scene graph branch.

**Comment by ericchristenson** [comment]
Looks good.

**Comment by dislogical** [comment]
:a:

**Comment by brooklynlittell** [comment]
:+1:

**Pull request merged**
