### PR TITLE
Feature: Sharing is Caring

### LINKED ISSUE #74: Migrate to Shared
This will allow us to multithread any part of the engine we deem necessary.

### PR DESCRIPTION
**Pull request by dislogical**
This pull request contains the initial migration to `shared`, which will allow future parallelization.

See Sample-Dash-Game/feature/concurrency for a demo.

Closes #74.

### CODE REVIEW

**Comment by ericchristenson** [comment]
Still nervous, but I guess we can fix/change things as we need to in the future since it works fine on a single thread for now.

**Comment by brooklynlittell** [comment]
Is Travis a non-issue?

**Comment by dislogical** [comment]
There's a branch on Game that matches this, and without it the build fails.

**Comment by brooklynlittell** [comment]
Gotcha. Looks good! :+1:

**Pull request merged**
