### PR TITLE
Feature: Engine State

### LINKED ISSUE #120: Change GameState to EngineState, Update Flags
We're modifying the internal state enum to only consist of three states: Running, Exit, Reset. This issue also consists of exposing flags to the game so devs may control when engine components get updated.

### PR DESCRIPTION
**Pull request by brooklynlittell**
Closes #120.

### CODE REVIEW

**Comment by dislogical** [comment]
:a:

**Comment by PxlBuzzard** [comment]
:penguin:

**Comment by tmr9209** [comment]
All good

**Comment by ericchristenson** [comment]
:100: Lets go get food.

**Pull request merged**
