### PR TITLE
Feature: New logging system

### PR DESCRIPTION
**Pull request by NCrashed**
Original issue: https://github.com/Circular-Studios/Dash/issues/149
- Old staff is marked with 'deprecated'
- There are two phases: before loading a config (default config is used)
  and after config is loaded (logger could change logging file)
- There is feature to setup verbosity levels both for outputing to
  console and outputing to file
- Configuration is loaded in error-proof manner. All values are set to
  default if config cannot find them
- Fully qualified logging section in config:

``` YAML
Game:
    Verbosity: !Verbosity High # OutputManager 
Logging: # GlobalLogger options
    FilePath: "dash.log" # Phase 2 logname
    Debug: # Is taken in debug build
        OutputVerbosity: !Verbosity High
        LoggingVerbosity: !Verbosity High
    Release: # Is taken in release build
        OutputVerbosity: !Verbosity High
        LoggingVerbosity: !Verbosity High
```

### CODE REVIEW

**Comment by dislogical** [comment]
I have to say I'm very impressed with this. I'm a huge fan of the quality of code here.

The only question I have is about how the Output vs. Logging works. Does a call to the `log()` function handle both the stdio logging and the file logging (assuming verbosity is proper)?

**Comment by NCrashed** [comment]
There is actually two `log` functions:
Deprecated one (old behavior, prints to console only)

```
void log( A... )( OutputType type, A messages ) 
```

Logger one that actually should be used:

```
void log( A... )( LoggingLevel type, lazy A messages )
```

Last function prints to console and to file simultaneously . There is two parameters in logger to control output behavior:
- `minOutputLevel` - handles minimal `LoggingLevel` values that goes to console
- `minLoggingLevel` - handles minimal `LoggingLevel` values that goes to file

**Comment by dislogical** [comment]
Okay. The part where it prints to the console and to the file was the part I was curious about.

Having looked over all of the code, I can say LGTM :+1:

**Comment by PxlBuzzard** [comment]
Awesome stuff, this will make both the engine and game folks happier.

**Comment by dislogical** [comment]
The only thing that I think I would suggest is to mark the [logError](https://github.com/Circular-Studios/Dash/pull/155/files#diff-9eb2116e3abe039e5bba76edfcdaefcfR69) and [logInfo](https://github.com/Circular-Studios/Dash/pull/155/files#diff-9eb2116e3abe039e5bba76edfcdaefcfR63) aliases as deprecated, so that way we can remove them in 0.8.0.

**Comment by wozniakty** [comment]
Looks great man. Awesome turnaround. :+1:

**Comment by NCrashed** [comment]
I found that my dlogg package also uses [logInfo](https://github.com/NCrashed/dlogg/blob/master/source/dlogg/log.d#L141) and `logError` names for wrappers. 

Deprecating the names here also implies deprecating dlogg API (that affect a ton of code), I haven't yet decided how to synchronize wrappers names with loggging level names in the best way. Perhaps it just not a good idea.

**Comment by dislogical** [comment]
In that case, I think it's fine to keep them.

**Comment by brooklynlittell** [comment]
Looks good! :+1:

**Pull request merged**
