### PR TITLE
Feature: Reload Yaml

### PR DESCRIPTION
**Pull request by dislogical**
You can now set the `currentState` in game to `Resetting` to reload all content.

Relies on #57.

### CODE REVIEW

**Comment by PxlBuzzard** [comment]
Literally two thumbs up. :thumbsup: :thumbsup:

**Comment by wozniakty** [comment]
:+1:

**Comment by brooklynlittell** [comment]
:+1:

**Comment by tmr9209** [comment]
Looks good to me.

**Pull request merged**
